# Generated by Django 4.2.14 on 2024-08-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('player_email', models.EmailField(db_index=True, max_length=125, unique=True)),
                ('player_password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PlayerBasicInfo',
                'db_table': 'PlayerBasicInfo',
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_won_games', models.IntegerField(default=0)),
                ('player_level', models.IntegerField(default=0)),
                ('player_rank', models.CharField(choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('Semi-Pro', 'Semi-Pro'), ('Pro', 'Pro'), ('World Class', 'World Class'), ('Legendary', 'Legendary'), ('Ultimate', 'Ultimate')], default='Beginner', max_length=20)),
                ('player_lost_games', models.IntegerField(default=0)),
                ('player_draw_games', models.IntegerField(default=0)),
                ('player_won_tournaments', models.IntegerField(default=0)),
                ('player_total_tournaments', models.IntegerField(default=0)),
                ('player_experience_points', models.IntegerField(default=0)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.playerbasicinfo')),
            ],
            options={
                'verbose_name': 'PlayerGameStats',
                'db_table': 'PlayerGameStats',
            },
        ),
        migrations.CreateModel(
            name='PlayerDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_first_name', models.CharField(max_length=30)),
                ('player_last_name', models.CharField(max_length=30)),
                ('player_starting_date', models.DateTimeField()),
                ('player_avatar', models.ImageField(null=True, upload_to='avatars/')),
                ('player_gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('N', 'N')], default='N', max_length=2)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.playerbasicinfo')),
            ],
            options={
                'verbose_name': 'PlayerDetailInfo',
                'db_table': 'PlayerDetailInfo',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_type', models.CharField(choices=[('Friend Request', 'Friend Request'), ('Game Request', 'Game Request'), ('Game Result', 'Game Result'), ('Chat', 'Chat'), ('Tournament', 'Tournament')], max_length=20)),
                ('notification_content', models.TextField()),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_is_read', models.BooleanField(default=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_notification', to='API.playerbasicinfo')),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('player_1_score', models.IntegerField(default=0)),
                ('player_2_score', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='API.playerbasicinfo')),
                ('player_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='API.playerbasicinfo')),
            ],
            options={
                'verbose_name': 'GameResults',
                'db_table': 'GameResults',
                'indexes': [models.Index(fields=['player_1_id', 'player_2_id'], name='GameResults_player__1be712_idx')],
            },
        ),
        migrations.CreateModel(
            name='FriendshipList',
            fields=[
                ('friendship_date', models.DateTimeField(auto_now_add=True)),
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='API.playerbasicinfo')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='API.playerbasicinfo')),
            ],
            options={
                'verbose_name': 'FriendshipList',
                'db_table': 'FriendshipList',
                'indexes': [models.Index(fields=['player_id', 'friend_id'], name='FriendshipL_player__b713f4_idx')],
                'unique_together': {('player_id', 'friend_id')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('friend_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to='API.playerbasicinfo')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to='API.playerbasicinfo')),
            ],
            options={
                'verbose_name': 'FriendRequests',
                'db_table': 'FriendRequests',
                'indexes': [models.Index(fields=['sender_id', 'receiver_id'], name='FriendReque_sender__49e4ab_idx')],
                'unique_together': {('sender_id', 'receiver_id')},
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('message_content', models.TextField()),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='API.playerbasicinfo')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='API.playerbasicinfo')),
            ],
            options={
                'verbose_name': 'Conversation',
                'db_table': 'Conversation',
                'indexes': [models.Index(fields=['sender_id', 'receiver_id'], name='Conversatio_sender__d3165c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_status', models.CharField(choices=[('chatted', 'chatted'), ('not_chatted', 'not_chatted')], default='not_chatted', max_length=20)),
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1_instance', to='API.playerbasicinfo')),
                ('player_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2_instance', to='API.playerbasicinfo')),
            ],
            options={
                'verbose_name': 'Chat',
                'db_table': 'Chat',
                'indexes': [models.Index(fields=['player_1_id', 'player_2_id'], name='Chat_player__4798bc_idx')],
                'unique_together': {('player_1_id', 'player_2_id')},
            },
        ),
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_of_block', models.DateTimeField(auto_now_add=True)),
                ('blocked_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='API.playerbasicinfo')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to='API.playerbasicinfo')),
            ],
            options={
                'verbose_name': 'BlockList',
                'db_table': 'BlockList',
                'indexes': [models.Index(fields=['player_id', 'blocked_id'], name='BlockList_player__93bce5_idx')],
                'unique_together': {('player_id', 'blocked_id')},
            },
        ),
    ]
