# Generated by Django 4.2.14 on 2024-08-05 09:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('player_starting_date', models.DateTimeField()),
                ('player_avatar', models.ImageField(null=True, upload_to='avatars/')),
                ('player_gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('N', 'N')], default='N', max_length=2)),
            ],
            options={
                'verbose_name': 'PlayerInfo',
                'verbose_name_plural': 'PlayerInfo',
                'db_table': 'PlayerInfo',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='blocklist',
            options={'verbose_name': 'BlockList', 'verbose_name_plural': 'BlockList'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chat'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversation'},
        ),
        migrations.AlterModelOptions(
            name='friendrequests',
            options={'verbose_name': 'FriendRequests', 'verbose_name_plural': 'FriendRequests'},
        ),
        migrations.AlterModelOptions(
            name='friendshiplist',
            options={'verbose_name': 'FriendshipList', 'verbose_name_plural': 'FriendshipList'},
        ),
        migrations.AlterModelOptions(
            name='gameresults',
            options={'verbose_name': 'GameResults', 'verbose_name_plural': 'GameResults'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notification'},
        ),
        migrations.AlterModelOptions(
            name='playergamestats',
            options={'verbose_name': 'PlayerGameStats', 'verbose_name_plural': 'PlayerGameStats'},
        ),
        migrations.AlterField(
            model_name='friendrequests',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='PlayerDetailInfo',
        ),
        migrations.AlterField(
            model_name='blocklist',
            name='blocked_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='blocklist',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='player_1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1_instance', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='player_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2_instance', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='friendrequests',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='friendrequests',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='friendshiplist',
            name='friend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='friendshiplist',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='gameresults',
            name='player_1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='gameresults',
            name='player_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_notification', to='API.playerinfo'),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_gme_stats', to='API.playerinfo'),
        ),
        migrations.DeleteModel(
            name='PlayerBasicInfo',
        ),
    ]
