# Generated by Django 4.2.14 on 2024-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_playerinfo_alter_blocklist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinfo',
            name='player_starting_date',
        ),
        migrations.AlterField(
            model_name='friendrequests',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
