# Generated by Django 4.2.14 on 2024-08-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_playerinfo_player_starting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='player_username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='friendrequests',
            name='request_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
