# Generated by Django 4.2.14 on 2024-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_playerinfo_player_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinfo',
            name='player_username',
        ),
        migrations.AlterField(
            model_name='friendrequests',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=20),
        ),
    ]
