# Generated by Django 4.2.14 on 2024-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_playerinfo_player_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='player_gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('N', 'N')], default='N', max_length=2, null=True),
        ),
    ]
