# Generated by Django 4.2.14 on 2024-08-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_playerinfo_player_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergamestats',
            old_name='player_draw_games',
            new_name='draw_games',
        ),
        migrations.RenameField(
            model_name='playergamestats',
            old_name='player_experience_points',
            new_name='experience_points',
        ),
        migrations.RenameField(
            model_name='playergamestats',
            old_name='player_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='playergamestats',
            old_name='player_lost_games',
            new_name='lost_games',
        ),
        migrations.RenameField(
            model_name='playergamestats',
            old_name='player_rank',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='playergamestats',
            old_name='player_total_tournaments',
            new_name='total_tournaments',
        ),
        migrations.RenameField(
            model_name='playergamestats',
            old_name='player_won_games',
            new_name='won_games',
        ),
        migrations.RenameField(
            model_name='playergamestats',
            old_name='player_won_tournaments',
            new_name='won_tournaments',
        ),
        migrations.RenameField(
            model_name='playerinfo',
            old_name='player_avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='playerinfo',
            old_name='player_gender',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='friendrequests',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
