# Generated by Django 4.2.14 on 2024-08-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_rename_player_draw_games_playergamestats_draw_games_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequests',
            name='request_status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=20),
        ),
    ]
